### ISSUE TITLE
“值消失”问题的解释存在错误

### ISSUE THREAD

**Issue by ouuan** [THUSE-Course/course-index#1]
文档以及课件中对“值消失”问题给出的解释是“两次更新很近”，但实际上的原因是 state 在每次渲染中都有一个 snapshot，即使是在 `setTimeout` 等场合中访问，并不“两次更新很近”，也会导致这一问题，现在的这种解释可能有一定的误导。

reference: <https://beta.reactjs.org/learn/state-as-a-snapshot>

**Comment by Ashitemaru** [comment]
Accepted & Fixed.
